-- NinaList Database Schema Setup
-- Run these queries in your Supabase SQL Editor to create the necessary tables.

-- 1. Create Media Collection Table
CREATE TABLE IF NOT EXISTS public.collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Anime', 'Manga', 'Manhwa', 'Manhua')),
    status TEXT NOT NULL CHECK (status IN ('Watching', 'Completed', 'Plan to Watch')),
    genre TEXT,
    rating NUMERIC DEFAULT 0,
    progress_current INTEGER DEFAULT 0 NOT NULL,
    progress_total INTEGER DEFAULT 0 NOT NULL,
    cover_image TEXT
);

ALTER TABLE public.collection ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.collection DROP CONSTRAINT IF EXISTS collection_type_check;
ALTER TABLE public.collection ADD CONSTRAINT collection_type_check CHECK (type IN ('Anime', 'Manga', 'Manhwa', 'Manhua'));

-- Public read-only access for collection.
-- Admin insert/update/delete happen through the Next.js API using SUPABASE_SERVICE_ROLE_KEY
-- (service_role bypasses RLS — do NOT use the anon key on the server).
DROP POLICY IF EXISTS "Allow public insert to collection" ON public.collection;
DROP POLICY IF EXISTS "Allow public update to collection" ON public.collection;
DROP POLICY IF EXISTS "Allow public delete to collection" ON public.collection;

DROP POLICY IF EXISTS "Allow public read access to collection" ON public.collection;
CREATE POLICY "Allow public read access to collection" ON public.collection
    FOR SELECT TO anon, authenticated USING (true);

-- 2. Create Community Suggestions Table
CREATE TABLE IF NOT EXISTS public.suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Anime', 'Manga', 'Manhwa', 'Manhua')),
    description TEXT,
    status TEXT NOT NULL DEFAULT 'Pending Review',
    votes INTEGER DEFAULT 0 NOT NULL,
    cover_image TEXT
);

ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.suggestions DROP CONSTRAINT IF EXISTS suggestions_type_check;
ALTER TABLE public.suggestions ADD CONSTRAINT suggestions_type_check CHECK (type IN ('Anime', 'Manga', 'Manhwa', 'Manhua'));

CREATE POLICY "Allow public read access to suggestions" ON public.suggestions
    FOR SELECT TO anon USING (true);

CREATE POLICY "Allow public insert to suggestions" ON public.suggestions
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Allow public update to suggestions" ON public.suggestions
    FOR UPDATE TO anon USING (true);

-- 3. Activity Log Table (powers dashboard recent activity, streak, and heatmap)
CREATE TABLE IF NOT EXISTS public.activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    action TEXT NOT NULL CHECK (action IN ('watched_episode', 'read_chapter', 'completed_series', 'added_entry', 'updated_rating')),
    item_id BIGINT,
    title TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    media_type TEXT
);

ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access to activity_log" ON public.activity_log;
CREATE POLICY "Allow public read access to activity_log" ON public.activity_log
    FOR SELECT TO anon USING (true);

-- Writes to activity_log are performed by the admin API using the service role key.
